env: LunarLander-v2
featExtractor: !!python/name:core.NothingToDo ''
freqOptim: 1000
freqSave: 5000
freqTest: 10000
freqVerbose: 100000
fromFile: null
maxLengthTest: 500
maxLengthTrain: 500
nbEpisodes: 500000
nbTest: 1
seed: 5


clip: false
kl: False

K_epochs: 5
discount: 0.999
gae_lambda: 0.99
entropy: False
entropy_coef: 0.0001
eps_clip: 0.2
delta: 0.01
beta: 1

lr_a: 0.0002
lr_c: 0.0002