env: CartPole-v1                                                  # environnement
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 10
nbTest: 1
freqVerbose: 1000
freqOptim: 1                                                                          # Optimisation de la politique tous les freqOptim evenements
fromFile: null
nbEpisodes: 1000  000
maxLengthTrain: 500
maxLengthTest: 1000
