env: Pendulum-v0                                                  # environnement
seed: 5
freqSave: 1000
freqTest: 100
nbTest: 1
freqVerbose: 1000
freqOptim: 10                                                                          # Optimisation de la politique tous les freqOptim evenements
fromFile: null
nbEpisodes: 1000000
maxLengthTrain: 300
maxLengthTest: 500
