C: 10
decay: 0.99999
discount: 0.999
env: LunarLander-v2
eps: 0.1
featExtractor: !!python/name:core.NothingToDo ''
freqOptim: 1
freqSave: 1000
freqTest: 10
freqVerbose: 10
fromFile: null
lr: 3e-4
maxLengthTest: 1000
maxLengthTrain: 500
mem_size: 1000
mini_batch_size: 10
nbEpisodes: 1000000
nbTest: 1
seed: 5
