env: LunarLander-v2   
seed: 0   
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 500
nbTest: 10
freqVerbose: 50000
freqOptim: 2000                                                                         # Optimisation de la politique tous les freqOptim evenements
fromFile: null
nbEpisodes: 30000
maxLengthTest: 200                                                                    # Longueur maxi des trajectoires en Test
maxLengthTrain: 200                                                                   # Longueur maxi des trajectoires en Train
target_update: 500
epoch_ppo: 10
epoch_disc: 10
discount: 0.99
gae_lambda: 0.95
entropy: True
entropy_coef: 0.001
eps_clip: 0.2
device: 0

lr_a: 0.0002
lr_c: 0.0002
lr_d: 0.0002
