K_epochs: 5
clip: true
env: LunarLander-v2
featExtractor: !!python/name:core.NothingToDo ''
freqOptim: 500
freqSave: 1000
freqTest: 50000
freqVerbose: 50000
fromFile: null
kl: false
maxLengthTest: 500
maxLengthTrain: 500
nbEpisodes: 3000
nbTest: 10
seed: 5


clip: True
kl: False

K_epochs: 5
discount: 0.999
gae_lambda: 0.99
entropy: True
entropy_coef: 0.0001
eps_clip: 0.2
delta: 0.01
beta: 1

lr_a: 0.0002
lr_c: 0.0002