env: LunarLander-v2
featExtractor: !!python/name:core.NothingToDo ''
freqOptim: 1000
freqSave: 5000
freqTest: 10000
freqVerbose: 100000
fromFile: null
maxLengthTest: 500
maxLengthTrain: 500
nbEpisodes: 500000
nbTest: 1
seed: 5
