commit: 'dcab2f7f1c35772863ce16d3ef621ee424767864 refs/heads/main

  aa66ecf22840abb5ca81f4891ad50d17bd38e61d refs/heads/master

  dcab2f7f1c35772863ce16d3ef621ee424767864 refs/remotes/origin/HEAD

  dcab2f7f1c35772863ce16d3ef621ee424767864 refs/remotes/origin/main

  '
device: 0
discount: 0.99
entropy: true
entropy_coef: 0.001
env: LunarLander-v2
epoch_disc: 7
epoch_ppo: 20
eps_clip: 0.2
featExtractor: !!python/name:core.NothingToDo ''
freqOptim: 400
freqSave: 1000
freqTest: 500
freqVerbose: 50000
fromFile: null
gae_lambda: 0.95
lr_a: 0.0002
lr_c: 0.0002
lr_d: 0.0002
maxLengthTest: 200
maxLengthTrain: 200
nbEpisodes: 30000
nbTest: 10
seed: 0
target_update: 500
